name: 'Colin Forster'
description: 'git diff of folders'
author: 'col inc'
inputs:
  folders:
    description: 'list of fodlers to check for changes'
    required: true
    default: 'extensions, services, migrations'
outputs:
  to_build:
    description: 'json object of which apps to build'
runs:
  using: 'node16'
  main: 'dist/index.js'
